### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by MakaveliN1** [Eternal-Walnut/Apex-NoRecoil-Alpha#10]
Is it possible to add controller support? Since this uses mouse_event i assume there will be something similar for joy sticks idk.. Is it worth looking into?

**Comment by Eternal-Walnut** [comment]
I used to support controller, but there were issues with sensitivity calculations

**Comment by MakaveliN1** [comment]
> I used to support controller, but there were issues with sensitivity calculations

Is it possible to get the old build which has controller support? Thanks!

**Comment by Eternal-Walnut** [comment]
> > I used to support controller, but there were issues with sensitivity calculations
> 
> Is it possible to get the old build which has controller support? Thanks!

no, because I deleted it

**Comment by MakaveliN1** [comment]
> > > I used to support controller, but there were issues with sensitivity calculations
> > 
> > 
> > Is it possible to get the old build which has controller support? Thanks!
> 
> no, because I deleted it

sadge, can u possibly point me to the right direction like a documentation or smt which allows u to emulate controller stick movement for recoil control? Thank you!

**Comment by Eternal-Walnut** [comment]
> sadge, can u possibly point me to the right direction like a documentation or smt which allows u to emulate controller stick movement for recoil control? Thank you!

https://www.autohotkey.com/boards/viewtopic.php?t=29659
