### ISSUE TITLE
UUID_generator.exe这个要怎么使用呢？

### ISSUE THREAD

**Issue by sjiebn** [Eternal-Walnut/Apex-NoRecoil-Alpha#12]
双击进去后，弹出报错窗口
![Image_1697184327814](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/49134233/e255da00-ac2a-499e-b38d-31a52cc8d3d8)

**Comment by Eternal-Walnut** [comment]
把apexmaster.ahk改成paircs就行
没必要用

**Comment by MakaveliN1** [comment]
Update the UpdateUUID Method as:
This explicitly sets the working directory to script directory and then extracts the directory from absolute path
`
def updateUUID(filename, new_uuid):
    script_dir = os.path.dirname(os.path.abspath(__file__))  # Get the directory of the script
    file_path = os.path.join(script_dir, filename)  # Create the full path to the file
    
    with open(file_path, "r") as f:
        content = f.read()

    new_uuid_str = 'global UUID := "' + new_uuid + '"'

    content_new = re.sub('global UUID := ".+"', new_uuid_str, content)

    with open(file_path, "w") as f:
        f.write(content_new)
`

**Comment by sjiebn** [comment]
> 把apexmaster.ahk改成paircs就行 没必要用

谢谢大佬
