### ISSUE TITLE
武器專精等級100等

### ISSUE THREAD

**Issue by et50710et** [Eternal-Walnut/Apex-NoRecoil-Alpha#17]
武器專精等級100後壓槍效果消失 右下角武器欄武器圖案有特效

**Comment by Eternal-Walnut** [comment]
can you send screenshot?

**Comment by et50710et** [comment]
![螢幕擷取畫面 2023-11-18 203157](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/150679614/5ac89575-5ece-4860-84b5-a571be368c61)

**Comment by et50710et** [comment]
If the weapon is level 100, the effect will disappear.

**Comment by Eternal-Walnut** [comment]
我沒有一把武器等級是100 所以我目前不會修復這個問題
