### ISSUE TITLE
Hello, I have a question

### ISSUE THREAD

**Issue by zq95888** [Eternal-Walnut/Apex-NoRecoil-Alpha#22]
After downloading and decompressing, I received a prompt stating that the hyde.dll file could not be parsed。I replaced the previous version of hyde.dll and ran the gui.ahk file, but found it invalid.Then I replaced the gui.ahk file you wrote with the previous version and found it to be effective. I don't know where the problem occurred, maybe I was too foolish myself. I hope you can reply to me.By the way, I don't know English. I translated it using Baidu. I know you because I asked questions before and you helped me answer them. I am familiar with you, haha

**Comment by Eternal-Walnut** [comment]
It is not recommended to use GUI. for modifying options, you can directly change the settings.ini file

**Comment by zq95888** [comment]
How can I start the GUI if I don't use it? I saw someone say before that using GUI can enable it, so I only use GUI to play Apex

**Comment by Eternal-Walnut** [comment]
Double-Click apexmaster.ahk
