### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by sky5416841** [Eternal-Walnut/Apex-NoRecoil-Alpha#23]
https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/5f86581b-34ea-4ef2-8fb4-2efe7e6eb809

I opened the file Gui.ahk, but the program 'apexmaster.ahk' did not appear. I'm not sure if it executed successfully.

I'm not good at English. I used ChatGPT to translate this

**Comment by MoralFst** [comment]
It's running. He added #NoTrayIcon on line 9 to hide the icon.

**Comment by sky5416841** [comment]
How do I close this program? If it is running

**Comment by MoralFst** [comment]
END key on keyboard .

**Comment by Eternal-Walnut** [comment]
Yes, I added #NoTrayIcon to hide the tray icon. If you need it, you can delete this line of code

**Comment by sky5416841** [comment]
OK thx
