### ISSUE TITLE
patterns not working after guns are lvl 100

### ISSUE THREAD

**Issue by na101n** [Eternal-Walnut/Apex-NoRecoil-Alpha#25]
my flatline stopped working after i level it to 100 with debug it says default and all the other guns are working normally even when I'm on my smurf account the flatline works good so I'm sure the problem is from the gun level and also I'm sure it stopped working because after level 100 in inventory the gun is in a different color so i just want to know how to get the hex code of the flatline and what i have to change in the script to make it work again

**Comment by Garren134** [comment]
To find the coordinates u use pmeter and make it show cursor coordinates which then you change in the resolution notepad, u can also find the hex color of the glowing effect with show color picker, but i dont know how to change the script to make it recognize that one.

**Comment by Eternal-Walnut** [comment]
It is very difficult to make all level 100 weapons at all resolutions support this script because the points scanned at each resolution are different, resulting in different colors

When one of my weapons reaches level 100, I may try to support its normal operation at 1920x1200 resolution
