### ISSUE TITLE
您好，我想问个问题

### ISSUE THREAD

**Issue by mengshang233** [Eternal-Walnut/Apex-NoRecoil-Alpha#27]
After running apexmaster. ahk and gui.ahk, isn't there a program in the background? Why is it not available now? If I want to close it, how can I close it? Can I only restart it?

**Comment by biqigubafan1** [comment]
press end to finish it

**Comment by mengshang233** [comment]
> 按结束键完成它

Where is the end button?

**Comment by biqigubafan1** [comment]
on your keyboard，my god
