### ISSUE TITLE
在我使用ReShade里的Technicolor2模式将画面修改更为鲜艳时出现了一些问题，我重新识别了轻、重、能量等武器的颜色，但在代码中修改颜色后仅能正常识别轻型与重型的武器，在识别能量武器时只有在双持能量武器时才能正常识别，老哥知道为什么吗？

### ISSUE THREAD

**Issue by xslzlccc** [Eternal-Walnut/Apex-NoRecoil-Alpha#32]
在我使用ReShade里的Technicolor2模式将画面修改更为鲜艳时出现了一些问题，我重新识别了轻、重、能量等武器的颜色，但在代码中修改颜色后仅能正常识别轻型与重型的武器，在识别能量武器时只有在双持能量武器时才能正常识别，老哥知道为什么吗？
鲜艳轻型颜色：global LIGHT_WEAPON_COLOR := 0x2D547D
鲜艳重型颜色：global HEAVY_WEAPON_COLOR := 0x596B38
鲜艳能量颜色：global ENERGY_WEAPON_COLOR := 0x286E5A
鲜艳霰弹枪颜色：global SHOTGUN_WEAPON_COLOR := 0x07206B
鲜艳狙击枪颜色：global SNIPER_WEAPON_COLOR := 0x8F404B
鲜艳塞拉颜色：global SELLA_WEAPON_COLOR := 0xA13CA1
鲜艳充能复仇颜色：target_color := 0xD6BD62

**Comment by na101n** [comment]
can i ask how did you get the color codes and did you change the patterns

**Comment by xslzlccc** [comment]
> can i ask how did you get the color codes and did you change the patterns

https://www.youtube.com/watch?v=VhpEi4_U3lc

**Comment by xslzlccc** [comment]
问题解决了，能量武器颜色采集的时候出了问题，我晕。
求关闭issue，太蠢了。
