### ISSUE TITLE
Shutter Lag 

### ISSUE THREAD

**Issue by Badguyyyy** [Eternal-Walnut/Apex-NoRecoil-Alpha#34]
when i press SPACEBAR my game is SHUTTER LAG and FREAM DROP 
using ver ss21 last updated

**Comment by na101n** [comment]
i get shutter lag from the when i open the script so it stay all the time not just when i press space this started to happen after the last update i tried to change the value of the mouse delay but nothing happened

**Comment by Eternal-Walnut** [comment]
#35
