### ISSUE TITLE
Spacebar spam

### ISSUE THREAD

**Issue by Garren134** [Eternal-Walnut/Apex-NoRecoil-Alpha#35]
it spams spacebar when i try to climb or just try to jump in general

**Comment by Badguyyyy** [comment]
same problem when try to climb wall

**Comment by sky5416841** [comment]
![image](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/4a7a8e52-c5d7-4734-8617-cb9cd8edf8cc)
He add !bhop I think just delete it

**Comment by Badguyyyy** [comment]
i will try

**Comment by Badguyyyy** [comment]
> ![image](https://private-user-images.githubusercontent.com/109945433/330411776-4a7a8e52-c5d7-4734-8617-cb9cd8edf8cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTEyNDQsIm5iZiI6MTcxNTY5MDk0NCwicGF0aCI6Ii8xMDk5NDU0MzMvMzMwNDExNzc2LTRhN2E4ZTUyLWM1ZDctNDczNC04NjE3LWNiOWNkOGVkZjhjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMjQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjhjNTkxNDY2MDk4YTlhN2E0YmNjNTZjYjFiMjYwNzU2ZGYyMzk4YmUzYmU0NTkyYmM3NDIzMmI5YTZjNGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5b4zBUVRPp3KU9FOiCWBY-PxZVae3oZEPpUuC4E8pA4) He add !bhop I think just delete it

my problem is fixed now bro thanks you
