### ISSUE TITLE
请问一下，我在游戏里不想使用它了，如何关闭它，后台我并没有看到，求解答

### ISSUE THREAD

**Issue by natiekafei** [Eternal-Walnut/Apex-NoRecoil-Alpha#36]

**Comment by natiekafei** [comment]
如果有人看见，可以帮助我吗？If anyone sees it, can you help me？

**Comment by sky5416841** [comment]
鍵盤上面的 END鍵 按一下就關閉了

**Comment by natiekafei** [comment]
> 鍵盤上面的 END鍵 按一下就關閉了
我在游戏里面按了END，并没有关闭压枪，我尝试在桌面按END，也没有关闭压枪，请问在哪里按END才能关闭它
