### ISSUE TITLE
LAG problem

### ISSUE THREAD

**Issue by sky5416841** [Eternal-Walnut/Apex-NoRecoil-Alpha#37]
https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/40923934-9388-4ce2-ab6d-566ce703f952

不開APEX NORECOIL FPS能穩定100 並且不會顯示延遲之類的圖案 
當我打開APEX NORECOIL 滑鼠只要移動FPS就會大跌 只要滑鼠一直移動畫面就會卡死 射擊會出現大延遲 

"Without opening APEX NORECOIL, the FPS can stay stable at 100 without displaying any latency-related patterns. However, when I open APEX NORECOIL, the FPS drops significantly whenever I move the mouse. If I keep moving the mouse continuously, the screen freezes and there's a noticeable delay in shooting."(By ChatGPT)

**Comment by MoralFst** [comment]
I modified this slightly and tested it myself without the above problem.
Overwrite the past and try to see.
[apexmaster.txt](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/files/15312589/apexmaster.txt)

**Comment by sky5416841** [comment]
> 我稍微修改了一下，然後自己測試了一下，沒有出現上述問題。覆蓋過去並嘗試查看。 [apexmaster.txt](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/files/15312589/apexmaster.txt)
No Recoil is functional.
But The lag issue remains the same
Whenever I open apexmaster.ahk, the game's ping becomes very high, and moving the mouse causes the FPS to drop significantly
I'm not sure what the problem is

**Comment by sky5416841** [comment]
> I modified this slightly and tested it myself without the above problem. Overwrite the past and try to see. [apexmaster.txt](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/files/15312589/apexmaster.txt)

No Recoil is functional.
But The lag issue remains the same
Whenever I open apexmaster.ahk, the game's ping becomes very high, and moving the mouse causes the FPS to drop significantly
I'm not sure what the problem is

**Comment by Eternal-Walnut** [comment]
我正在正常使用，沒有出現過此問題

**Comment by Eternal-Walnut** [comment]
我認為你可以使用任务管理器監測是哪個應用導致的CPU佔用异常 或者你可以嘗試不使用gui 直接使用apexmaster.ahk

**Comment by sky5416841** [comment]
> 我認為你可以使用任务管理器監測是哪個應用導致的CPU佔用异常 或者你可以嘗試不使用gui 直接使用apexmaster.ahk


https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/7ca5a640-41ce-403b-b42a-881eebfc1fcb

問題還是一樣 就一開AHK就會整個超卡 不知道是不是破爛熊的問題

**Comment by sky5416841** [comment]
![image](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/64b90fb9-82fc-4368-889f-0676016018ab)

mgsweet 那邊也有人反應 也許真的是hyde64.dll 造成遊戲卡頓 
開gui.ahk 那個畫面不會造成卡頓 按下Save and run 整個遊戲就開始卡了 

People on mgsweet have also reported similar issues; it may indeed be hyde64.dll causing the game to lag." (Chat GPT)

**Comment by Eternal-Walnut** [comment]
使用工作管理員看看是哪個應用程序導致的卡頓？

**Comment by Eternal-Walnut** [comment]
我的電腦上不會出現卡頓

**Comment by Eternal-Walnut** [comment]
哦 有一說一 你應該將apexmaster.ahk編譯成exe後使用 而不是直接使用使用AutoHotKey執行ahk 這樣可能存在被檢測的風險

**Comment by sky5416841** [comment]
> 哦 有一說一 你應該將apexmaster.ahk編譯成exe後使用 而不是直接使用使用AutoHotKey執行ahk 這樣可能存在被檢測的風險

我晚點試試看

**Comment by sky5416841** [comment]
![image](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/d766f095-9deb-4e20-a23a-8e8f703c6c21)
看來是沒辦法 這段限制了exe

**Comment by Eternal-Walnut** [comment]
> Author

什麼是“限制了exe”？

**Comment by sky5416841** [comment]
就轉成 exe 就跳這段 MsgBox, Mixed Versions detected!`nOS Version and AHK Version need to be the same (x86 & AHK32 or x64 & AHK64).`n`nScript will now terminate!

**Comment by sky5416841** [comment]
![image](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/66fddc11-6a1f-40d4-8115-6b613bfbbf5d)
感覺真的是hyde64.dll的問題 把他禁用之後就沒出現卡頓的問題 壓槍也能正常的運作

**Comment by sky5416841** [comment]
https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/c7146f9d-ab5e-4585-9aac-70f03f5b0222

**Comment by MoralFst** [comment]
> ![image](https://private-user-images.githubusercontent.com/109945433/331826339-66fddc11-6a1f-40d4-8115-6b613bfbbf5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjE1NzcsIm5iZiI6MTcxNjA2MTI3NywicGF0aCI6Ii8xMDk5NDU0MzMvMzMxODI2MzM5LTY2ZmRkYzExLTZhMWYtNDBkNC04MTE1LTZiNjEzYmZiYmY1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxOTQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDM3YzQ3YjIxOTgzYzQ4NzNjOGU0MzIxMGM5YjQzOTkwMGE5ODI4ODQyMGQzODYyYmNkMzI3Zjg1NGZiMzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZLUpvYG17givbTnGSkAM70vo22Uh5w93_MbqZOqwNrI) 感覺真的是hyde64.dll的問題 把他禁用之後就沒出現卡頓的問題 壓槍也能正常的運作

This means that your program process is no longer hidden and has a greater risk of being detected.

**Comment by sky5416841** [comment]
> > ![image](https://private-user-images.githubusercontent.com/109945433/331826339-66fddc11-6a1f-40d4-8115-6b613bfbbf5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjE1NzcsIm5iZiI6MTcxNjA2MTI3NywicGF0aCI6Ii8xMDk5NDU0MzMvMzMxODI2MzM5LTY2ZmRkYzExLTZhMWYtNDBkNC04MTE1LTZiNjEzYmZiYmY1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxOTQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDM3YzQ3YjIxOTgzYzQ4NzNjOGU0MzIxMGM5YjQzOTkwMGE5ODI4ODQyMGQzODYyYmNkMzI3Zjg1NGZiMzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZLUpvYG17givbTnGSkAM70vo22Uh5w93_MbqZOqwNrI) 感覺真的是hyde64.dll的問題 把他禁用之後就沒出現卡頓的問題 壓槍也能正常的運作
> 
> This means that your program process is no longer hidden and has a greater risk of being detected.

![image](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/109945433/4aa9b3f6-34d8-4fc8-ab01-30bb318d0e4f)
But EAC can already detect hyde64.dll

**Comment by GouldX** [comment]
> ![image](https://private-user-images.githubusercontent.com/109945433/331826339-66fddc11-6a1f-40d4-8115-6b613bfbbf5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDU5MzAsIm5iZiI6MTcxNjEwNTYzMCwicGF0aCI6Ii8xMDk5NDU0MzMvMzMxODI2MzM5LTY2ZmRkYzExLTZhMWYtNDBkNC04MTE1LTZiNjEzYmZiYmY1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwODAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTc4MzZlZTQ0NmM4ZWE4NzlhNDQ1ODY0N2ZhODczNGM4M2EzNTBmNTAyYTRjOGIxYTI5OGRmOTBjMzQ0ZDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7CHyW-OcjdLIyEXe_xIJqP9TY5VdMFlnhOdHyajbQPg) 感覺真的是hyde64.dll的問題 把他禁用之後就沒出現卡頓的問題 壓槍也能正常的運作

請問你是如何禁用它的，我不會PYTHON，只學你在前面加了/*和*/仍然沒有禁用成功

**Comment by Eternal-Walnut** [comment]
好吧，雖然hyde64在我的電腦上正常工作，但是我會添加一個不使用hyde64的版本供hyde64被檢測到的用戶使用
