### ISSUE TITLE
Fps drops and stutter when i press any keys with the scripts on

### ISSUE THREAD

**Issue by GouldX** [Eternal-Walnut/Apex-NoRecoil-Alpha#38]
Fps drops and stutter when i press any keys with the scripts on , but if i standing still without pressing any keys ,its working fine
打開腳本之後只要我按任何一個鍵，都會卡頓
![_20240515105754](https://github.com/Eternal-Walnut/Apex-NoRecoil-Alpha/assets/164628835/7886d641-d582-4ea4-b63f-d93c4f812103)

**Comment by Eternal-Walnut** [comment]
我正在正常使用，沒有出現過此問題

**Comment by GouldX** [comment]
目前發現的解決方法是按住其他鍵的時候再按一下别的鍵，就會停止卡頓，但是鬆開後再次按鍵仍然會卡頓。so far i found the only solution is press any other keys when holding any key and its suttering ,but it'd still stutter after release it

**Comment by natiekafei** [comment]
> 目前發現的解決方法是按住其他鍵的時候再按一下别的鍵，就會停止卡頓，但是鬆開後再次按鍵仍然會卡頓。到目前为止，我发现唯一的解决方案是在按住任何键时按任何其他键及其断断续续，但松开后仍然会卡顿

是的，我也会卡頓

**Comment by Eternal-Walnut** [comment]
可以試一下關閉bhop？
