### ISSUE TITLE
Pattern updates?

### ISSUE THREAD

**Issue by NicktheQuick33** [Eternal-Walnut/Apex-NoRecoil-Alpha#43]
I've inspected all the patterns and only the Havoc and R99 are out of date. The Alternator passable. The rest are good.
I know how the script works, but does anyone know how to measure the patterns to start with? (slow-mo video etc?)

**Comment by NicktheQuick33** [comment]
Also, Season 20 R99 pattern is better than Season 23 for this season (24).

**Comment by Eternal-Walnut** [comment]
![image](https://github.com/user-attachments/assets/a84848a5-6486-4523-adb6-6eeaa7c3fc0c)
