### ISSUE TITLE
P2020 is not working So I try Fix .  Is work  

### ISSUE THREAD

**Issue by sky5416841** [Eternal-Walnut/Apex-NoRecoil-Alpha#46]
Old not work 
p2020 = "1609,970,1,1633,981,0,1650,1004,1"

New is work 
p2020 = "1597,978,1,1625,978,0,1646,1011,1"

I can't Pull requests 

I only fixed it for 1920x1080.
I haven't fixed the others.

![image](https://github.com/user-attachments/assets/8582df53-d616-454c-ab29-dfe66ebee2db)

**Comment by Eternal-Walnut** [comment]
Oh, I forgot P2020

**Comment by Eternal-Walnut** [comment]
Maybe I still need to test for dual

**Comment by sky5416841** [comment]
The dual guns don't need to, they can fire continuously. / 雙槍不需要 他本來就可以連發 
Mozambique, it can detect even dual guns. 莫三他雙槍都可以偵測到 不需要更動

**Comment by Eternal-Walnut** [comment]
> The dual guns don't need to, they can fire continuously. / 雙槍不需要 他本來就可以連發 Mozambique, it can detect even dual guns. 莫三他雙槍都可以偵測到 不需要更動

是不是双枪可以通过判断切换单发的那个白点判断，我目前没时间更新 所以暂时搁置一会

**Comment by sky5416841** [comment]
> > The dual guns don't need to, they can fire continuously. / 雙槍不需要 他本來就可以連發 Mozambique, it can detect even dual guns. 莫三他雙槍都可以偵測到 不需要更動
> 
> 是不是双枪可以通过判断切换单发的那个白点判断，我目前没时间更新 所以暂时搁置一会

這我就不知道了 主要是單發不能按著連發  (他P2020是用槍枝上的兩個白色 跟一個灰色來判斷的 應該是這樣沒錯 我是拿之前的P2020定位點來用的) 我用小畫家慢慢找定位點 Debug後就能偵測到了

**Comment by Eternal-Walnut** [comment]
> > > The dual guns don't need to, they can fire continuously. / 雙槍不需要 他本來就可以連發 Mozambique, it can detect even dual guns. 莫三他雙槍都可以偵測到 不需要更動
> > 
> > 
> > 是不是双枪可以通过判断切换单发的那个白点判断，我目前没时间更新 所以暂时搁置一会
> 
> 這我就不知道了 主要是單發不能按著連發 (他P2020是用槍枝上的兩個白色 跟一個灰色來判斷的 應該是這樣沒錯 我是拿之前的P2020定位點來用的) 我用小畫家慢慢找定位點 Debug後就能偵測到了

![image](https://github.com/user-attachments/assets/bc95842d-5963-4ed1-bd92-ce3b970aead4)
你只需要使用现成的CheckSingleMode方法即可判断目前是双持还是单持
