### ISSUE TITLE
开启脚本后游戏卡死

### ISSUE THREAD

**Issue by Npc-gugugu** [Eternal-Walnut/Apex-NoRecoil-Alpha#48]
关闭脚本后游戏又可以正常运行
![1](https://github.com/user-attachments/assets/7396d8fe-d93a-49ed-918b-f837029fe53a)

**Comment by Badguyyyy** [comment]
i think ahk is now detected

**Comment by Eternal-Walnut** [comment]
use [without_hyde64](https://github.com/hackersense/Apex-NoRecoil-Alpha/blob/main/AHK/src/apexmaster_without_hyde64.ahk)

**Comment by Npc-gugugu** [comment]
昨天更新后又可以工作了
