### ISSUE TITLE
I think EasyAntiCheat know

### ISSUE THREAD

**Issue by NicktheQuick33** [Eternal-Walnut/Apex-NoRecoil-Alpha#49]
Apex crashes only when running AHK now.
Looks like we're scuppered, chaps.

**Comment by NicktheQuick33** [comment]
I've tried renaming the gui and apexmaster files to .exe within the script, then compiling the files into executable files with no luck. I wonder if EasyAntiCheat is looking at the Frame and RGB buffers and seeing if anything other than r5Apex is calling them?

**Comment by hitch3ns** [comment]
its working now again

**Comment by Eternal-Walnut** [comment]
use [without_hyde64](https://github.com/hackersense/Apex-NoRecoil-Alpha/blob/main/AHK/src/apexmaster_without_hyde64.ahk)

**Comment by NicktheQuick33** [comment]
> use [without_hyde64](https://github.com/hackersense/Apex-NoRecoil-Alpha/blob/main/AHK/src/apexmaster_without_hyde64.ahk)

Legend! Changed my buttons and UID in the script and it's all working. Is there an Akimbo pattern?

**Comment by hitch3ns** [comment]
it worked back without changing anything if it worth it how to change UID ?
