### ISSUE TITLE
Script not working in fullscreen

### ISSUE THREAD

**Issue by ghost** [Eternal-Walnut/Apex-NoRecoil-Alpha#7]
I don't know if I'm using it wrong but the script doesn't work in TRUE fullscreen mode for me. it only works in BorderlessWindow...is this normal?

If you don't know what true fullscreen is, watch this:
https://www.youtube.com/watch?v=HOhToUiBWj8

**Comment by KulldarBOi** [comment]
What res are you using?

**Comment by ghost** [comment]
1920 X 1080

**Comment by KulldarBOi** [comment]
Most likely ini file got broken, though this script has some pattern problems across all resolutions, so gotta wait until eternal is gonna fix this shit.

**Comment by ghost** [comment]
But if I were to enable the "True Fullscreen Mode" in my registry, is the script still supposed to work?
or would it work in something like windowed mode?

**Comment by KulldarBOi** [comment]
Try to reset that setting in registry prompt back to default, and see If it will work.

**Comment by ghost** [comment]
It does but It would be nice if the script could work with the registry change.
The "True Fullscreen" mode makes the game run better and feel more responsive

**Comment by Eternal-Walnut** [comment]
Due to AutoHotKey limitations, this issue may not be fixed
