### ISSUE TITLE
发现一个bug，在使用几小时后，大约4小时以后，就会失效

### ISSUE THREAD

**Issue by jingleifan1** [Eternal-Walnut/Apex-NoRecoil-Alpha#9]
大约都是4小时以后，使用就会失效，测试发现只有重启电脑才可以，并不是所有武器都失效，电脑1920*1080，失效包括 301，赫姆洛克、复仇女神失效，不会失效:平行步枪、r99、car,同时，能否帮忙增加一个e或r的检测机制，当前切换1或2 当速度过快，发现不生效，速度慢打近战会被揍

**Comment by Eternal-Walnut** [comment]
沒遇到過。。。
